### ISSUE TITLE
Data lengths differ from paper

### ISSUE THREAD

**Issue by adrian-jaques-b** [yilingchung/multilingualCN-classification#1]
Hello,

first of all, thank you for sharing your work. I really appreciate that!

Here comes my question:
I wanted to use your dataset-splits for comparable experiments with different models. 
When I checked the data I noticed that the lengths of the splits described in the paper do not match the lengths of the data in your github repo. 

![image](https://user-images.githubusercontent.com/68905111/181590530-5a3cdaf5-c143-4152-ba5a-a019f8c72c30.png)

![image](https://user-images.githubusercontent.com/68905111/181590152-feb0d14c-69ea-4d64-ac3e-e37531c142ea.png)

Did you may upload the wrong splits or am I just interpreting something wrong?

Thank you a lot!
- Jaqu

**Comment by yilingchung** [comment]
Hi @JaquJaqu, thanks for pointing that out!

The data size in the github repo is the same as Table 2 in the paper as you attached, for 5 classes: "facts", "denouncing", "question", "hypocrisy", and "humor".

<img width="496" alt="Screenshot 2022-08-01 at 17 55 27" src="https://user-images.githubusercontent.com/9419045/182202517-0ffe7f21-11bc-4ec5-93a9-70aa6601cefb.png">

The additional pairs in the file are for 2 classes, "support" and "unrelated", in which we randomly created for training/testing. We used them as negative examples, considering that CONAN dataset contains only positive examples of counter narratives (CNs). We include them to ensure that the models are exposed to varied non-CN text. 

Since the 2 classes are not relevant to proper CNs, we only report the number of examples for the above 5 classes (Table 2) and the performance over these 5 classes. See more detail in last paragraph in section 3.1 in the paper.

You can decide whether you want to use the additional 2 classes. Let me know if this clarifies :)

**Comment by adrian-jaques-b** [comment]
Oh I see! Thank you for your fast reply. Now it's clear to me! :)
